## ------------------------------------------------------------
## Script: All/scripts/21_consumer_link_support_profiles.R
##
## Purpose:
## Descriptive consumer-only analysis of absolute local support of
## realised interaction links.
##
## This script uses the shared 10-dataset helper/loader file:
##   All/scripts/00_dataset_loaders_and_helpers_all.R
##
## It does not fit models, run null models, use beta-binomial models,
## or run site-removal simulations.
## ------------------------------------------------------------

source("All/scripts/00_dataset_loaders_and_helpers_all.R")

set.seed(123)

## ---------------------------
## Settings and output folders
## ---------------------------

result_type <- "script21_consumer_link_support_profiles"
dirs <- make_output_dirs(result_type)
sep_out <- dirs$separated
combined_out <- dirs$combined

## Use only the original 10 datasets defined in the helper script.
datasets_to_run <- all_dataset_names

## ---------------------------
## Small local helpers
## ---------------------------

make_pair_id <- function(consumer, resource){
  paste(consumer, resource, sep = "___")
}

safe_cor_spearman <- function(x, y){
  ok <- is.finite(x) & is.finite(y)
  x <- x[ok]
  y <- y[ok]
  if(length(x) < 3) return(NA_real_)
  if(length(unique(x)) < 2 || length(unique(y)) < 2) return(NA_real_)
  suppressWarnings(cor(x, y, method = "spearman"))
}

build_realised_link_table <- function(dataset){
  site_tables <- get_dataset_site_tables(dataset)

  cooc <- site_tables$cooc_triples %>%
    distinct(site, consumer, resource) %>%
    mutate(pair_id = make_pair_id(consumer, resource))

  ints <- site_tables$empirical_site_interactions %>%
    distinct(site, consumer, resource) %>%
    mutate(pair_id = make_pair_id(consumer, resource))

  ## Defensive consistency check: an interaction cell should be one of the
  ## operational co-occurrence cells generated by the shared helper.
  missing_interaction_cells <- anti_join(
    ints %>% select(site, consumer, resource),
    cooc %>% select(site, consumer, resource),
    by = c("site", "consumer", "resource")
  )

  if(nrow(missing_interaction_cells) > 0){
    warning(dataset, ": ", nrow(missing_interaction_cells),
            " interaction cells were not present in cooc_triples. Adding them defensively.")
    cooc <- bind_rows(
      cooc %>% select(site, consumer, resource, pair_id),
      missing_interaction_cells %>%
        mutate(pair_id = make_pair_id(consumer, resource))
    ) %>%
      distinct(site, consumer, resource, pair_id)
  }

  cooc_counts <- cooc %>%
    group_by(dataset = dataset, consumer, resource, pair_id) %>%
    summarise(n = n_distinct(site), .groups = "drop")

  int_counts <- ints %>%
    group_by(pair_id) %>%
    summarise(K = n_distinct(site), .groups = "drop")

  cooc_counts %>%
    left_join(int_counts, by = "pair_id") %>%
    mutate(
      K = replace_na(K, 0L),
      realised_link = K > 0,
      repeatability = ifelse(n > 0, K / n, NA_real_)
    ) %>%
    filter(realised_link) %>%
    select(dataset, consumer, resource, pair_id, n, K, repeatability)
}

make_consumer_profiles <- function(link_table){
  link_table %>%
    group_by(dataset, consumer) %>%
    summarise(
      full_degree = n_distinct(resource),
      mean_K = mean(K, na.rm = TRUE),
      median_K = median(K, na.rm = TRUE),
      min_K = min(K, na.rm = TRUE),
      max_K = max(K, na.rm = TRUE),
      proportion_K1 = mean(K == 1, na.rm = TRUE),
      proportion_K2_or_less = mean(K <= 2, na.rm = TRUE),
      mean_n = mean(n, na.rm = TRUE),
      mean_repeatability = mean(repeatability, na.rm = TRUE),
      n_realised_links_used = n(),
      .groups = "drop"
    )
}

make_summary_tests <- function(profiles){
  bind_rows(
    data.frame(
      dataset = unique(profiles$dataset),
      test_name = "Degree vs absolute link support",
      spearman_correlation = safe_cor_spearman(profiles$full_degree, profiles$mean_K),
      number_of_consumers = nrow(profiles)
    ),
    data.frame(
      dataset = unique(profiles$dataset),
      test_name = "Degree vs one-site links",
      spearman_correlation = safe_cor_spearman(profiles$full_degree, profiles$proportion_K1),
      number_of_consumers = nrow(profiles)
    ),
    data.frame(
      dataset = unique(profiles$dataset),
      test_name = "Degree vs co-occurrence opportunity",
      spearman_correlation = safe_cor_spearman(profiles$full_degree, profiles$mean_n),
      number_of_consumers = nrow(profiles)
    ),
    data.frame(
      dataset = unique(profiles$dataset),
      test_name = "Degree vs repeatability",
      spearman_correlation = safe_cor_spearman(profiles$full_degree, profiles$mean_repeatability),
      number_of_consumers = nrow(profiles)
    )
  )
}

make_checks <- function(dataset, link_table, profiles){
  data.frame(
    dataset = dataset,
    all_realised_links_have_K_at_least_1 = all(link_table$K >= 1),
    all_realised_links_have_K_less_equal_n = all(link_table$K <= link_table$n),
    consumer_proportions_between_0_and_1 =
      all(profiles$proportion_K1 >= 0 & profiles$proportion_K1 <= 1) &&
      all(profiles$proportion_K2_or_less >= 0 & profiles$proportion_K2_or_less <= 1),
    full_degree_equals_links_used = all(profiles$full_degree == profiles$n_realised_links_used),
    no_models_simulations_or_site_removal_used = TRUE,
    n_consumers = nrow(profiles),
    n_realised_links = nrow(link_table)
  )
}

run_one_dataset <- function(dataset){
  message("Running script 21 consumer link support profiles: ", dataset)

  dataset_dir <- file.path(sep_out, dataset)
  dir.create(dataset_dir, recursive = TRUE, showWarnings = FALSE)

  link_table <- build_realised_link_table(dataset)
  profiles <- make_consumer_profiles(link_table)
  summary_tests <- make_summary_tests(profiles)
  checks <- make_checks(dataset, link_table, profiles)

  write.csv2(link_table,
             file.path(dataset_dir, paste0(dataset, "_21_realised_link_support.csv")),
             row.names = FALSE)
  write.csv2(profiles,
             file.path(dataset_dir, paste0(dataset, "_21_consumer_link_support_profiles.csv")),
             row.names = FALSE)
  write.csv2(summary_tests,
             file.path(dataset_dir, paste0(dataset, "_21_consumer_link_support_summary.csv")),
             row.names = FALSE)
  write.csv2(checks,
             file.path(dataset_dir, paste0(dataset, "_21_consumer_link_support_checks.csv")),
             row.names = FALSE)

  list(
    links = link_table,
    profiles = profiles,
    summary = summary_tests,
    checks = checks
  )
}

## ---------------------------
## Run analysis
## ---------------------------

all_outputs <- lapply(datasets_to_run, run_one_dataset)
names(all_outputs) <- datasets_to_run

link_table_all <- bind_rows(lapply(all_outputs, `[[`, "links"))
profiles_all <- bind_rows(lapply(all_outputs, `[[`, "profiles"))
summary_all <- bind_rows(lapply(all_outputs, `[[`, "summary"))
checks_all <- bind_rows(lapply(all_outputs, `[[`, "checks"))

profiles_all <- profiles_all %>%
  mutate(dataset = factor(dataset, levels = datasets_to_run))

summary_all <- summary_all %>%
  mutate(
    dataset = factor(dataset, levels = datasets_to_run),
    test_name = factor(
      test_name,
      levels = c(
        "Degree vs absolute link support",
        "Degree vs one-site links",
        "Degree vs co-occurrence opportunity",
        "Degree vs repeatability"
      )
    )
  )

write.csv2(
  profiles_all,
  file.path(combined_out, "21_consumer_link_support_profiles.csv"),
  row.names = FALSE
)

write.csv2(
  summary_all,
  file.path(combined_out, "21_consumer_link_support_summary.csv"),
  row.names = FALSE
)

write.csv2(
  checks_all,
  file.path(combined_out, "21_consumer_link_support_checks.csv"),
  row.names = FALSE
)

## ---------------------------
## Validation
## ---------------------------

message("\nScript 21 validation checks:")
print(checks_all)

if(any(!checks_all$all_realised_links_have_K_at_least_1) ||
   any(!checks_all$all_realised_links_have_K_less_equal_n) ||
   any(!checks_all$consumer_proportions_between_0_and_1) ||
   any(!checks_all$full_degree_equals_links_used) ||
   any(!checks_all$no_models_simulations_or_site_removal_used)){
  stop("Script 21 validation failed. Inspect 21_consumer_link_support_checks.csv")
}

## ---------------------------
## Figures
## ---------------------------

point_colour <- "grey20"
line_colour <- "#0072B2"

base_scatter_theme <- theme_classic(base_size = 10) +
  theme(
    legend.position = "bottom",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold")
  )

p1 <- ggplot(profiles_all,
             aes(x = full_degree, y = mean_K)) +
  geom_point(aes(colour = "Consumers"), alpha = 0.75, size = 1.7) +
  geom_smooth(aes(colour = "Linear guide"),
              method = "lm", se = TRUE, linewidth = 0.9) +
  scale_colour_manual(values = c("Consumers" = point_colour,
                                 "Linear guide" = line_colour),
                      name = "") +
  facet_wrap(~ dataset, ncol = 5, scales = "free") +
  base_scatter_theme +
  xlab("Number of realised resource partners") +
  ylab("Mean number of sites per realised link")

ggsave(
  file.path(combined_out, "21_degree_absolute_link_support.png"),
  p1,
  width = 14,
  height = 7,
  dpi = 300
)

p2 <- ggplot(profiles_all,
             aes(x = full_degree, y = proportion_K1)) +
  geom_point(aes(colour = "Consumers"), alpha = 0.75, size = 1.7) +
  geom_smooth(aes(colour = "Linear guide"),
              method = "lm", se = TRUE, linewidth = 0.9) +
  scale_colour_manual(values = c("Consumers" = point_colour,
                                 "Linear guide" = line_colour),
                      name = "") +
  facet_wrap(~ dataset, ncol = 5, scales = "free_x") +
  coord_cartesian(ylim = c(0, 1)) +
  base_scatter_theme +
  xlab("Number of realised resource partners") +
  ylab("Fraction of realised links observed in one site")

ggsave(
  file.path(combined_out, "21_degree_one_site_links.png"),
  p2,
  width = 14,
  height = 7,
  dpi = 300
)

p3 <- ggplot(profiles_all,
             aes(x = full_degree, y = mean_n)) +
  geom_point(aes(colour = "Consumers"), alpha = 0.75, size = 1.7) +
  geom_smooth(aes(colour = "Linear guide"),
              method = "lm", se = TRUE, linewidth = 0.9) +
  scale_colour_manual(values = c("Consumers" = point_colour,
                                 "Linear guide" = line_colour),
                      name = "") +
  facet_wrap(~ dataset, ncol = 5, scales = "free") +
  base_scatter_theme +
  xlab("Number of realised resource partners") +
  ylab("Mean number of co-occurring sites per realised link")

ggsave(
  file.path(combined_out, "21_degree_cooccurrence_opportunity.png"),
  p3,
  width = 14,
  height = 7,
  dpi = 300
)

summary_colours <- c(
  "Degree vs absolute link support" = "#0072B2",
  "Degree vs one-site links" = "#D55E00",
  "Degree vs co-occurrence opportunity" = "#009E73",
  "Degree vs repeatability" = "#CC79A7"
)

p4 <- ggplot(summary_all,
             aes(x = dataset, y = spearman_correlation, colour = test_name)) +
  geom_hline(yintercept = 0, colour = "grey55") +
  geom_point(size = 2.3, position = position_dodge(width = 0.55), na.rm = TRUE) +
  scale_colour_manual(values = summary_colours, name = "") +
  facet_grid(test_name ~ ., scales = "free_y") +
  theme_classic(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    strip.background = element_blank(),
    strip.text.y = element_text(angle = 0, hjust = 0)
  ) +
  xlab("") +
  ylab("Spearman correlation")

ggsave(
  file.path(combined_out, "21_consumer_link_support_summary.png"),
  p4,
  width = 12,
  height = 9,
  dpi = 300
)

message("\nScript 21 summary:")
print(summary_all)

message("\nFinished script 21. Outputs saved in:")
message("  ", combined_out)
